name: deploy github packages (docker)

on: 
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build the Docker image
        run: docker build . -t docker.pkg.github.com/planetarium/ninechronicles.headless/ninechronicles-headless:git-${{ github.sha }} --build-arg COMMIT=git-${{ github.sha }}
      - name: login
        run: docker login docker.pkg.github.com -u '${{ secrets.GH_USERNAME }}' -p '${{ secrets.GH_ACCESS_TOKEN }}'
      - name: push git version
        run: docker push docker.pkg.github.com/planetarium/ninechronicles.headless/ninechronicles-headless:git-${{ github.sha }}
