name: update-submodule

on:
    push:
        branches:
            - rc-v*
            - release/*

jobs:
    update-submodule:
        if: github.ref_type == 'branch'
        runs-on: ubuntu-latest
        steps:
            - name: Update other repos referring NineChronicles.Headless as submodules
              uses: planetarium/submodule-updater@main
              with:
                  token: ${{ secrets.SUBMODULE_UPDATER_GH_TOKEN }}
                  committer: >
                      Submodule Updater <engineering+submodule-updater@planetariumhq.com>
                  targets: |
                      ${{ github.repository_owner }}/NineChronicles.DataProvider:${{ github.ref_name }}?
